description: '범민의 기술블로그입니다.'

email: club20608@gmail.com


archive_dir: archives
category_dir: categories
tag_dir: tags
rss_dir: atom.xml

social:
  github: https://github.com/parkbeommin
  
gitalk: 
  client_id: Ov23liRM1tBkguIjv9gn
  client_secret: 3839e8d5894b90df68f18fe77d3394206b969bab
  repo: parkbeommin.github.io
  owner: ParkBeomMin
  admin: ParkBeomMin
ga: G-44YWDK9DBE
  