description: '범민의 기술블로그입니다.'

email: club20608@gmail.com


archive_dir: archives
category_dir: categories
tag_dir: tags
rss_dir: atom.xml

social:
  github: https://github.com/parkbeommin
  
giscus:
  repo: ParkBeomMin/parkbeommin.github.io
  repo_id: REPO_ID_HERE
  category: General
  category_id: CATEGORY_ID_HERE
  mapping: pathname
  theme: light
ga: G-44YWDK9DBE
  